# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20171015_1802'),
        ('lists', '0006_auto_20171018_2214'),
    ]

    operations = [
    ]
